ingress:
  enabled: true
  annotations: 
    kubernetes.io/ingress.class: nginx
  path: /
  hosts:
    - kibana.35.240.104.250.xip.io

tolerations:  
  - key: node-role    
    operator: Equal    
    value: infra    
    effect: NoSchedule

nodeSelector:
  cloud.google.com/gke-nodepool: infra-pool

resources:
  requests:
    cpu: "600m"
    memory: "2Gi"
  limits:
    cpu: "600m"
    memory: "2Gi"