grafana:
  enabled: true

  adminPassword: Password1!

  ingress:
    enabled: true
    annotations: 
      kubernetes.io/ingress.class: nginx
    path: /
    hosts:
      - grafana.35.240.104.250.xip.io

  additionalDataSources:
    - name: Loki
      type: Loki
      access: proxy
      url: http://loki:3100

prometheus:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
    serviceMonitorSelector: {}
    serviceMonitorNamespaceSelector: {}

  ingress:
    enabled: true
    annotations: 
      kubernetes.io/ingress.class: nginx
    path: /
    hosts:
      - prometheus.35.240.104.250.xip.io