apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: shop-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: shop.35.240.107.92.nip.io
    http:
      paths:
      - backend:
          serviceName: frontend
          servicePort: 80
